# gh-pages 分支部署
name: Deploy the reference site to AliESC server

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  release:
    name: Deploy...
    runs-on: ubuntu-latest

    steps:
      # 检出 Git 仓库
      - name: Git clone
        run: git clone https://github.com/JingleCate/siteReference
      # 切换分支
      - name: Switch to static branch.
        run: |
            echo "Current dir: $(pwd)"
            git switch gh-pages
          
      - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@01a39e33483634cbd7ac99020c55b72ca7f098fe
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
          SOURCE: ./
          # Target directory
          TARGET: /var/www/html/jinglecath_inventory/
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          ARGS: "-avzr --delete" 
              
